//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIVING_HOPE_BAPTIST_CHURCH
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public byte[] MemberPic { get; set; }
        public string Auxiliary { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string WhatsApp { get; set; }
        public string Email { get; set; }
        public string Membership_Status { get; set; }
        public string Marital_Status { get; set; }
        public string Baptismal_Status { get; set; }
        public string Occupation { get; set; }
        public Nullable<System.DateTime> Baptismal_Year { get; set; }
        public Nullable<System.DateTime> Admission_Year { get; set; }
        public string Prev_Church { get; set; }
        public string Prev_Position { get; set; }
    }
}
